version: '3.8'

services:
  i9-feed-api:
    image: i9-feed-api:${VERSION:-homolog}
    container_name: i9-feed-api
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8001}:8000"
    environment:
      - TZ=America/Sao_Paulo
      - ENVIRONMENT=${ENVIRONMENT:-homolog}
      # Database
      - DATABASE_URL=${DATABASE_URL}
      # Redis
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      # JWT
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES:-1440}
      # API Keys
      - API_KEY_TABLETS=${API_KEY_TABLETS}
      # Application
      - APP_NAME=${APP_NAME:-i9 Smart Feed API}
      - APP_VERSION=${APP_VERSION:-1.0.0}
      - DEBUG=${DEBUG:-false}
      - SECRET_KEY=${SECRET_KEY}
      # CORS
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
      # MinIO/S3
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio:9000}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET:-feed-images}
      - MINIO_SECURE=${MINIO_SECURE:-false}
      # Upload limits
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-10485760}
      - ALLOWED_EXTENSIONS=${ALLOWED_EXTENSIONS:-jpg,jpeg,png,webp}
      # Feed configuration
      - MAX_IMAGES_PER_FEED=${MAX_IMAGES_PER_FEED:-50}
      - DEFAULT_DISPLAY_TIME=${DEFAULT_DISPLAY_TIME:-5000}
      - MIN_DISPLAY_TIME=${MIN_DISPLAY_TIME:-1000}
      - MAX_DISPLAY_TIME=${MAX_DISPLAY_TIME:-60000}
    volumes:
      # VOLUMES PERSISTENTES - NÃO SOBRESCREVER NO DEPLOY
      - feed-static:/app/static
      - feed-uploads:/app/uploads
      - feed-media:/app/media
      - feed-logs:/app/logs
      # Volume temporário para repositório (pode ser sobrescrito)
      - ./repo:/app/repo:ro
    networks:
      - i9-network
    labels:
      - "com.inoveon.project=i9-smart"
      - "com.inoveon.component=api"
      - "com.inoveon.service=feed"
      - "com.inoveon.version=${VERSION:-homolog}"
      - "com.inoveon.deploy.preserve=static,uploads,media,logs"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: i9-feed-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis-data:/data
      - redis-logs:/var/log/redis
    networks:
      - i9-network
    command: redis-server --appendonly yes --appendfsync everysec --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "com.inoveon.project=i9-smart"
      - "com.inoveon.component=cache"
      - "com.inoveon.service=redis"

networks:
  i9-network:
    driver: bridge
    name: i9-smart-feed-network

volumes:
  # VOLUMES PERSISTENTES - PRESERVADOS ENTRE DEPLOYS
  feed-static:
    driver: local
    labels:
      - "com.inoveon.preserve=true"
      - "com.inoveon.backup=daily"
  
  feed-uploads:
    driver: local
    labels:
      - "com.inoveon.preserve=true"
      - "com.inoveon.backup=daily"
  
  feed-media:
    driver: local
    labels:
      - "com.inoveon.preserve=true"
      - "com.inoveon.backup=daily"
  
  feed-logs:
    driver: local
    labels:
      - "com.inoveon.preserve=true"
      - "com.inoveon.backup=weekly"
  
  redis-data:
    driver: local
    labels:
      - "com.inoveon.preserve=true"
      - "com.inoveon.backup=daily"
  
  redis-logs:
    driver: local
    labels:
      - "com.inoveon.preserve=true"
      - "com.inoveon.backup=weekly"