"""Add preferences column to users table

Revision ID: 7706a43078a4
Revises: 0341e76f5bd0
Create Date: 2025-09-24 20:12:45.901160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7706a43078a4'
down_revision = '0341e76f5bd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###